title Блокировка звонков

alt Стандартная блокировка звонков

    Пользователь->Приложение: Нажатие на кнопку <...>
    Приложение->Пользователь: Список возможных действий
    
    Пользователь->Приложение: Нажатие на кнопку "Блокировать звонки"
    Приложение->Сервер: Окно подтверждения
    
    Пользователь->Приложение: Нажатие на кнопку <Да, блокировать звонки>

    Приложение->Сервер: Запрос на изменения данных

    alt Успешная блокировка

        Сервер->Приложение: Код успешной блокировки
        Приложение->Пользователь: Сообщение об успешной блокировке звонков



    else Ошибка блокировки

        Сервер->Приложение: Код ошибки блокировки
        Приложение->Пользователь: Сообщение об ошибке блокировки звонков

    end
