title Добавление в черный список

alt Стандартное добавление в черный список

    Пользователь->Приложение: Нажатие на кнопку <...>
    Приложение->Пользователь: Список возможных действий

    Пользователь->Приложение: Нажатие на кнопку "Добавить пользователя в черный список"
    Приложение->Сервер: Окно подтверждения
    
    Пользователь->Приложение: Нажатие на кнопку <Да, добавить в черный список>
    Приложение->Сервер: Запрос на изменения данных

    alt Успешное добавление

        Сервер->Приложение: Код успешного добавления
        Приложение->Пользователь: Сообщение об успешном добавлении в черный список



    else Ошибка добавления

        Сервер->Приложение: Код ошибки добавления
        Приложение->Пользователь: Сообщение об ошибке добавления

    end

